#!/bin/bash

rpis=( "rpi01" "rpi02" "rpi03" "rpi04" "rpi05" "rpi06" "rpi07" "rpi08" "rpi09" "rpi10" "rpi11" "rpi12" "rpi13" "rpi14" "rpi15" "rpi16" "rpi17" "rpi18" "rpi19" "rpi20" )

for i in "${rpis[@]}"
do
        :
        pingres=$(ping -q -c2 $i)
        cds="${pingres#**transmitted,}"
        newint="${cds%%received*}"
        lol="0"
        if [ $? -eq 0 ]
        then
                if [ $newint != $lol ]
                then
                        echo "$i : alive"
                else
                        echo "$i : dead"
                fi
        else
                echo "$i : dead"
        fi
done

exit 0
